spring:
  application:
    name: Pierro
  config:
    import: "classpath:exception-messages.yml"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/app
    username: postgres
    password: postgres
  flyway:
    enabled: true
    clean-disabled: false
  jpa:
    show-sql: on
    hibernate:
      ddl-auto: none
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
  web:
    resources:
      add-mappings: false

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%X{traceId}] %-5level %logger{36} - %msg%n"