ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'PROCURADOR_JURIDICO';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'AUTORIDADE_DESIGNANTE';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'AUTOR_TR';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'ACIONISTA';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'PROPRIETARIO';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'COMPANHEIRO';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'AVO_AVO';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'NETO_NETA';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'TIO_TIA';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'SOBRINHO_SOBRINHA';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'PRIMO_PRIMA';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'SOGRO_SOGRA';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'GENRO_NORA';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'CUNHADO_CUNHADA';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'PARENTESCO';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'FILIADO_PARTIDO';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'DIRIGENTE_PARTIDARIO';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'MEMBRO_DIRETORIO_PARTIDARIO';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'CANDIDATO';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'EX_CANDIDATO';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'RECEBEDOR_DOACAO';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'COORDENADOR_CAMPANHA';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'CABO_ELEITORAL';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'MANDATARIO';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'AGENTE_POLITICO';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'EX_EMPREGADOR';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'EX_EMPREGADO';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'COLEGA_TRABALHO';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'SOCIO_PROFISSIONAL';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'CONTRATANTE';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'CONTRATADO';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'CONSULTOR';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'ASSESSOR';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'GERENTE';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'ADMINISTRADOR';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'TRABALHISTA';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'MEMBRO_ASSOCIACAO';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'DIRETOR_ASSOCIACAO';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'PRESIDENTE_ASSOCIACAO';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'MEMBRO_ONG';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'DIRETOR_ONG';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'PRESIDENTE_ONG';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'MEMBRO_INSTITUTO';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'DIRETOR_INSTITUTO';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'MEMBRO_FUNDACAO';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'DIRETOR_FUNDACAO';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'MEMBRO_CONSELHO_ENTIDADE';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'DIRIGENTE_ENTIDADE';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'FUNDADOR_ENTIDADE';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'VOLUNTARIO_ENTIDADE';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'BENEFICIARIO_ENTIDADE';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'COMPARTILHA_TELEFONE';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'COMPARTILHA_EMAIL';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'COMPARTILHA_DOMINIO';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'COMPARTILHA_EMPRESA';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'COMPARTILHA_ENTIDADE';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'RELACAO_COMUM';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'MESMA_ORGANIZACAO';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'MESMO_CONSELHO';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'MESMA_DIRETORIA';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'AMIZADE';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'COLEGA_ACADEMICO';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'PROFESSOR';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'ALUNO';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'SERVIDOR_PUBLICO';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'AGENTE_PUBLICO';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'OCUPANTE_CARGO_COMISSIONADO';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'OCUPANTE_FUNCAO_PUBLICA';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'AUTORIDADE_PUBLICA';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'ORDENADOR_DESPESA';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'GESTOR_CONTRATO';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'FISCAL_CONTRATO';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'MEMBRO_COMISSAO_LICITACAO';
ALTER TYPE association_type ADD VALUE IF NOT EXISTS 'NAO_ESPECIFICADO';

ALTER TABLE business ADD COLUMN IF NOT EXISTS open_date date;

ALTER TABLE red_flags DROP COLUMN IF EXISTS actors_id CASCADE;

CREATE TABLE IF NOT EXISTS red_flags_actors (
    red_flag_id UUID NOT NULL,
    actor_id UUID NOT NULL,
    PRIMARY KEY (red_flag_id, actor_id),
    CONSTRAINT fk_red_flags_actors_red_flag FOREIGN KEY (red_flag_id) REFERENCES red_flags(id) ON DELETE CASCADE,
    CONSTRAINT fk_red_flags_actors_actor FOREIGN KEY (actor_id) REFERENCES actors(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_red_flags_actors_actor ON red_flags_actors(actor_id);


ALTER TABLE business
DROP COLUMN address;

ALTER TABLE people
DROP COLUMN address;

CREATE TABLE address(
    id UUID primary key DEFAULT gen_random_uuid(),
    postal_code char(8) NOT NULL,
    street_address varchar(255),
    number varchar(5),
    complement varchar(155),
    neighborhood varchar(100),
    city varchar(100),
    state char(2),
    actors_id UUID UNIQUE NOT NULL,
    constraint fk_actors_address
        foreign key (actors_id) references actors(id) on delete cascade
);

ALTER TABLE people
ADD COLUMN is_alive boolean DEFAULT true,
ADD COLUMN death_date date;